In [1]:
import numpy as np

In [3]:
#question1

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object = list_)

print("Data type of list_:", type(list_[0]))
print("Data type of array_list:", array_list.dtype)


Data type of list_: <class 'str'>
Data type of array_list: <U1


In [5]:
#question2


list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_)

for item in list_:
    print("Data type of element in list_:", type(item))

for item in array_list:
    print("Data type of element in array_list:", type(item))


Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>


In [6]:
#question3

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_, dtype=int)

for item in list_:
    print("Data type of element in list_:", type(item))

for item in array_list:
    print("Data type of element in array_list:", type(item))

Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>


In [7]:
#question4

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(num_list)

print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)

Shape of num_array: (2, 3)
Size of num_array: 6


In [8]:
#question5

zeros_array = np.zeros((3, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
#question6

identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
